In [9]:
%store -r team_data

In [10]:
import pandas as pd

In [11]:
# Ініціалізація початкових рейтингів для кожної команди (може бути будь-якими початковими значеннями)
initial_rating = 1500  # Початковий рейтинг Ело

# Створення словника для збереження рейтингів кожної команди
team_ratings = {team: initial_rating for team in team_data['Team']}

# Функція для розрахунку очікуваного результату матчу між командами A і B
def expected_result(rating_A, rating_B):
    return 1 / (1 + 10 ** ((rating_B - rating_A) / 400))

# Проходження через кожен матч і оновлення рейтингів
for index, row in final_df_2019_2023.iterrows():
    home_team = row['HomeTeam']
    away_team = row['AwayTeam']
    result = row['FTR']  # Результат матчу: 'H' - перемога вдома, 'A' - перемога на виїзді, 'D' - нічия
    
    # Отримання поточних рейтингів команд
    rating_home = team_ratings[home_team]
    rating_away = team_ratings[away_team]
    
    # Розрахунок очікуваного результату для кожної команди
    expected_home = expected_result(rating_home, rating_away)
    expected_away = expected_result(rating_away, rating_home)
    
    # Оновлення рейтингів команд на основі фактичного результату
    if result == 'H':
        team_ratings[home_team] = rating_home + 32 * (1 - expected_home)
        team_ratings[away_team] = rating_away + 32 * (0 - expected_away)
    elif result == 'A':
        team_ratings[home_team] = rating_home + 32 * (0 - expected_home)
        team_ratings[away_team] = rating_away + 32 * (1 - expected_away)
    else:  # 'D' - нічия
        team_ratings[home_team] = rating_home + 32 * (0.5 - expected_home)
        team_ratings[away_team] = rating_away + 32 * (0.5 - expected_away)

# Створення нового датасету з рейтингами команд
ratings_ELO_df = pd.DataFrame({'Team': list(team_ratings.keys()), 'Elo_Rating': list(team_ratings.values())})

In [12]:
ratings_ELO_df

           Team   Elo_Rating
0      Atalanta  1713.554987
1     Benevento  1395.379297
2       Bologna  1488.951320
3       Brescia  1363.813424
4      Cagliari  1459.519284
5     Cremonese  1405.181474
6       Crotone  1356.418041
7        Empoli  1437.078028
8    Fiorentina  1531.211068
9         Genoa  1470.127690
10        Inter  1740.246316
11     Juventus  1679.490400
12        Lazio  1645.826378
13        Lecce  1405.828176
14        Milan  1690.520913
15        Monza  1519.566564
16       Napoli  1627.520529
17        Parma  1459.320992
18         Roma  1631.086077
19  Salernitana  1421.516291
20    Sampdoria  1473.860697
21     Sassuolo  1553.236084
22         Spal  1314.906722
23       Spezia  1439.494072
24       Torino  1429.219391
25      Udinese  1493.953359
26      Venezia  1362.357363
27       Verona  1490.815063

In [13]:
%store ratings_ELO_df

Stored 'ratings_ELO_df' (DataFrame)